### ISSUE TITLE
Config not saving 

### ISSUE THREAD

**Issue by HighSunMurder** [Lissy93/dashy#1147]
### Environment

Self-Hosted (Docker)

### System

Ubuntu 

### Version

Current

### Describe the problem

Any changes i make in dashboard i save to disk via UI, If i reboot the server these changes are gone and dashy is vanilla /  default

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by ulysserevient** [comment]
Same problem here ! 
Unable to save conf.yml from the UI
The backup file is created, but the conf.yml isn't saved !

**Comment by ulysserevient** [comment]
I still can't save the conf file from the gui
is there a solution ?

**Comment by rongalbraith** [comment]
I have the same issue.  I get an error "AxiosError: Network Error".  This doesn't always happen and I'm trying to diagnose when it does currently.

**Comment by minisculemarch** [comment]
Same issue, regarding the file not saving but the backup is created. Rebuild also fails randomly, 503. I've found it easier to simply edit the conf file manually the restart the docker container.

**Comment by rongalbraith** [comment]
So, for me the answer was to implement a non-root installation for the container.  Not sure why it worked but there's obviously some conflict somewhere that doesn't occur when you're container is running under a non-root user.

Just added UID and GID environment variables:
    # Set any environmental variables
    environment:
    **# Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=1001
      - GID=1001**

Bear in mind that "1001" was my default user and your user may be different.  Quick _chown -R_ in the terminal for the folders where I was storing the persistent volume for Dashy, bounced the container and everything has been fine since.

**Comment by Glitch3dPenguin** [comment]
I have been having a similar issue. I’m going to give this a shot as well and see if I make and progress. Thanks for the recommendation!

**Comment by matteo-martinelli** [comment]
I have the same issue. Any kind of change is not update. Backups are made, but any change is effective.

**Comment by ulysserevient** [comment]
Hi,
I've tried to change UID and GID with non-root user, but problem persists !

**Comment by offline09** [comment]
Hi, I am having the same problem, set all my links up then boom, everything gone.  Tried the non-root user change, and still broken.

**Comment by strangedesign13** [comment]
Not sure if this is the intended design of dashy or if there is a bug, but what I finally found work had nothing to do root owner. After editing hit “Save to Disk” and then open the Update Configuration (the wrench icon) and then select “Rebuild Application”. After its success, i have had no issues with refreshing the dashboard, closing it and repointing it.

While saving a config doesn’t trigger the rebuild, I’m not sure but this has solved the issue for me.

**Comment by avaaum** [comment]
@Lissy93 i had this same issue that caused me to loose all my edits multiple times. edited fonts and colors did not stick after saving to disk multiple times, but menus, menu items and icons did. @strangedesign13's workaround above finally did the trick. i feel the expected behavior is for the "save to disk" function to trigger the "rebuild application" function. fwiw i'm using ff/librewolf and everything is up to date. plz look into this. thx again for your work. dashy is awesome :purple_heart:

**Comment by rootuser22** [comment]
Hi, 

I have an Ubuntu 22.04 VM running with Docker setup, I set up Dashy and had it configured to how I wanted, looked great etc.

Tested it with a reboot and docker didn't auto-start so I sorted that (see command history file)

Next, however, when I checked my Dashy, the config is reset...
[Dashy_commands.txt](https://github.com/Lissy93/dashy/files/12849723/Dashy_commands.txt)


I changed > Save to disk > tried the rebuild that @strangedesign13  suggests but it doesn't work.

I have attached my commands history, maybe someone can shed some light as to what's going on, please? @Lissy93

**Comment by strangedesign13** [comment]
> Hi,
> 
> I have an Ubuntu 22.04 VM running with Docker setup, I set up Dashy and had it configured to how I wanted, looked great etc.
> 
> Tested it with a reboot and docker didn't auto-start so I sorted that (see command history file)
> 
> Next, however, when I checked my Dashy, the config is reset... [Dashy_commands.txt](https://github.com/Lissy93/dashy/files/12849723/Dashy_commands.txt)
> 
> I changed > Save to disk > tried the rebuild that @strangedesign13 suggests but it doesn't work.
> 
> I have attached my commands history, maybe someone can shed some light as to what's going on, please? @Lissy93

Did you check that your Docker setup has persistent storage?

**Comment by TWCM** [comment]
go to Config > Enter Interactive editor > Edit App Config > Allow Config Editing  
Check the box, then you can use the save to disk button

**Comment by amitn322** [comment]
Same issue. Config gets reset.

**Comment by CrossPatch9000** [comment]
I had the same issue and resolved with the fix mentioned above. I made my edits, saved to disk, then went to Configuration Options and selected Rebuild Application and Reload Page. My changes then survived a reboot. A few more buttons to push, but works for me.

**Comment by AkshayRao27** [comment]
Another instance of the exact same issue. I'm running Dashy as a Debian 12 LXC Container on Proxmox 8. I installed it using the [Helper Scripts](https://tteck.github.io/Proxmox/). Using @strangedesign13's suggestion worked for me as well.

**Comment by vishalkadam7** [comment]
deployed on vercel

I get this error while trying to save config. is there any thing else that i need to configure in vercel to get the config saved

AxiosError: Request failed with
status code 405

**Comment by seraasch** [comment]
I got that error when the docker container stopped unexpectedly

**Comment by vdiogo** [comment]
Same issue! Actually new user, just started the configuration and with some refresh the configuration is all gone (including sample/ initial shortcuts, which I did not deleted).
Running Dashy in LXC

**Comment by Lissy93** [comment]
I think there may be a several different issues here, 

### Possible Issue 1: Unable to call save endpoint from CDN/static server
If you're running Dashy on a static host, like Vercel, then there's no server-side code to actually save the config, re: #1465 (this is outlined bit more in the docs)


### Possible Issue 2: Unable to save
In Docker, double check that the file isn't read-only, and that the container actually has permissions to modify it. You shouldn't really be running it as a `root` user, and I'm not sure if it will work if you do

### Possible Issue 3: Saved but not updating
After saving, the frontend will recompile, which may take a couple seconds (or a bit longer on a Pi or low-powered device). If it doesn't recompile, you can manually trigger a re-build.

### None of the above?
If you're still having issues, if you could share the following with me, it'll help me look into it further:
- If you open the conf.yml file, can you see your changes?
- When you save, are there any errors in the browser console (see: [how to open browser console](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console))
- Are there any errors in your Docker logs?

**Comment by CrazyWolf13** [comment]
Hi
This problems seems to be related to dashy not automatically rebuilding on changes (https://github.com/Lissy93/dashy/issues/1147#issuecomment-1633020158) , see #1479 and https://github.com/Lissy93/dashy/issues/1290#issuecomment-1884249018 
A new release has just been published, which should fix this issue, so please upgrade to the latest version.
If this is not the case just respond back to this ticket and I'll reopen this issue.
Thanks and have a nice day.

**Comment by wilcomir** [comment]
Hello,

I am still having issues with this - saving the configuration via the gui does not work properly.

I am using docker-compose, setting UID and GID to my user (1000:1000). I am passing through a whole folder to the container, permissions of the folder and all the files within are correct.

When I make a modification from the GUI, a backup file is created - therefore dashy can write to the folder - but the new conf.yaml is... not new, it's just the same. I see no error in the docker log, when I hit save a rebuild is correctly triggered, no error in the browser console as well.

I tried all permutations that I could think of, running the container without UID/GID, changing ownership of the folder to root:root, making the folder & contents chmod 777...

I am unsure how to proceed, I love this project and I am willing to perform any troubleshooting that might be necessary.

**Comment by rawGH** [comment]
I have the same exact issue. Dashy works. Installation/Configuration is done properly. I've been configuring Dashy for a couple of days now with little to no issues. However I am not able to edit config file via GUI. I mean I could do it the first time but never again after that. Changes are never really saved, even though saving confirmation is shown as successful. 
I've tried waiting, reloading and rebuilding with no success.

**Comment by shalithasuranga** [comment]
I had the save issue. Now, I just do preview changes -> save to disk from the JSON editor. This workaround works very well and is easy :tada:

**Comment by rawGH** [comment]
> I had the same issue. Now, I just do preview changes -> save to disk from the JSON editor. This workaround works very well and is easy 🎉

I've tested, but it does not work for me. I can edit "tree" (eg changing the order of sections) and save then, it works. Changes might require rebuild or reload page, but it works. The bug appears only when "code" is used and changed anything (even a string or something), it's never saved, using "Preview Changes" does nothing in this case.
When checking the actual files upon saving, two are affected. Backup and normal conf.yml, but contents are the same, as is the timestamp of both files, unfortunately the saved version is the previous one, so no actual changes were stored.

**Comment by Lissy93** [comment]
Try V3, there should be no more issues with this anymore

**Comment by rawGH** [comment]
Did a quick recreate docker to v3. Tested for about 10min, all seems to be working now. Thanks L.

**Comment by zaun** [comment]
I know this is old, but I'm on 3.1.1 docker and its not saving or updating the conf.yml file.

This is my launch script...

```
#!/bin/bash
set -euo pipefail

# Setup volumes and directories
sudo mkdir -p /home/podman/dashy/config
sudo chown -R podman:podman /home/podman/dashy

# Only write default config if it doesn't already exist
if [ ! -f /home/podman/dashy/config/conf.yml ]; then
  sudo tee /home/podman/dashy/config/conf.yml > /dev/null <<EOF
appConfig:
  title: Dashy
  theme: colorful
pages:
  - name: Default
    sections:
      - name: My Links
        items:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com
EOF
fi

# Run Dashy container
sudo podman run -d --name dashy \
  --replace \
  --network container-net \
  --ip 192.168.0.202 \
  -v /home/podman/dashy/config:/app/public/conf:Z \
  -e PORT=80 \
  -e HOST=0.0.0.0 \
  docker.io/lissy93/dashy:latest
```

I can run Dashy just fine, but if I edit something in the UI and click the "Save to Disk", I get the notification that it was successful, but the actual file isn't updated.

I verified its not a permission issue as I can `podman exec -it dashy sh` and edit the config file from within the container via vi.

Not sure if I'm missing something simple or not...
