### ISSUE TITLE
[BUG] Favicon not loading on page load

### ISSUE THREAD

**Issue by elendil7** [Lissy93/dashy#1588]
### Environment

Self-Hosted (Docker)

### System

Dashy running in Docker container behind Nginx

### Version

3.1.0

### Describe the problem

Dashy favicon no longer loads after update.

![image](https://github.com/Lissy93/dashy/assets/80429382/a8ce803f-f7a1-4fdb-9d23-cadf206c73cc)
![image](https://github.com/Lissy93/dashy/assets/80429382/79c0c6d2-8451-45ed-80cd-a9829ab4eb27)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi 
It's really hard with such less details to diagnose this, for me it's working totally fine.

Please share your nginx conf.
You can try clearing all browser cache and cookies, and try another browser in the private window.

**Comment by pelstob** [comment]
Hi, I'm running pretty much the same configuration and I'm having an issue with the favicon not showing in Firefox. This is using a fully cleared cache and also in a Private Window. I can't comment update breaking it, as I only switched back to Firefox from Brave a few hours ago. I get the same problem if I bypass the reverse proxy.

If I append the various /favicon.ico, /web-icons/favicon-32x32.png etc. listed in Firefox's inspector tab to the URL most of the icons are loading.
However, if I'm reading the Network Inspector tab correctly, then Firefox is trying to use https://home._mydomain_.org/img/icons/favicon-**16x16**.png but favicon-16x16.png doesn't exist. It's showing 404 not found in Firefox's inspector and as a directly accessed URI.

I think there are 2 issues here: The missing favicon-16x16.png and Firefox seemingly being determined to use the missing image, rather than fallback to favicon-32x32.png or favicon.ico.

Cheers.

**Comment by CrazyWolf13** [comment]
Yeah I've just looked into this and in firefox the favicon is not showing up at all.

Firefox still seems to have hardcoded a preferred size:
`view-source:resource:///modules/FaviconLoader.sys.mjs`
```
....
const FAVICON_PARSING_TIMEOUT = 100;
const FAVICON_RICH_ICON_MIN_WIDTH = 96;
const PREFERRED_WIDTH = 16;
....
```

I think  dashy is somewhat missing the correct variable to define the favicon for firefox, however I was not able to find any working variable. It seems that firefox has issues regarding favicon dating from a month ago to 20years back 😂

I tried adding the 16x16 pixel variant which was once included:
https://github.com/Lissy93/dashy/commit/7e4e2edc0cd494ce8c9e5126c5905e3879e2d9a3#diff-66c2900b7fcc62569ea372a2058eb4935e7559dcea7a3052b36d843a6e190734


But that did nothing, as firefox somehow expects a favicon on exactly this url:
![image](https://github.com/Lissy93/dashy/assets/96661824/7e1e1e56-144f-4689-bc9e-cc7b90531def)

**Comment by Lissy93** [comment]
Can confirm this bug, icon is not displaying on Firefox.
I'll submit a fix (by adding the appropriate icons in, and updating the paths in index.html) this weekend.

**Comment by alvarodev-lc** [comment]
Any updates on this? Firefox still doesn't load the favicon correctly for me.

**Comment by CrazyWolf13** [comment]
> I'll submit a fix (by adding the appropriate icons in, and updating the paths in index.html) this weekend.

@Lissy93 
Have you yet had time?

**Comment by Zixim** [comment]
Same issue, and with the new firefox vertical sidebar this is becoming particularly annoying, the whitespace in screenshot is where the favicon ought to be...
![Screenshot from 2024-07-31 10-34-29](https://github.com/user-attachments/assets/98819a87-67c5-49a7-ba4b-7e5f88bd9de2)

**Comment by m42cel** [comment]
@Lissy93 I'd like to *bump* this again. A fix would be highly appreciated. :)

**Comment by Zixim** [comment]
Pinging someone 3 months after they said they were going to do something can hardly be described as random.

**Comment by rdswords** [comment]
With today's image update, it's now working for me (Firefox). The favicon is back!

**Comment by CrazyWolf13** [comment]
Yup got fixed by a PR here:
https://github.com/Lissy93/dashy/pull/1678

**Comment by elendil7** [comment]
Thank you!
![image](https://github.com/user-attachments/assets/aa77351d-07cb-4240-866a-11e89841dd68)

**Comment by Zixim** [comment]
confirmed, thx for the merge !

**Comment by mpwhiten** [comment]
I'm seeing this issue still on my setup. I'm using dashy 3.1.1 via docker and the latest version of Firefox on Kubuntu 25.10.

The favicon shows up sporadically when on the holding page during the build process, but once the dashboard loads it's not showing. I've already tried clearing browser cache etc.

Any suggestions, or should I raise this as a new issue?


<img width="1011" height="245" alt="Image" src="https://github.com/user-attachments/assets/0a811277-fa2d-4d90-b5dd-2c73901a2a7c" />
