### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by mad-ady** [Lissy93/dashy#809]
### Environment

Self-Hosted (Docker)

### System

Ubuntu 22.04 running on arm64

### Version

2.1.1

### Describe the problem

First of all - thank you for your project! I can finally organize my home environment and stop having to remember 40 random ports :D

I've installed Dashy 2.1.1 via the docker-compose method. I mapped the configuration file to /etc/dashy.yml on my host (and gave it enough permissions to be writable). The docker instance started correctly. When I enter Config -> Enter the interactive editor and click on the "Add new section" in the GUI, I get the "Add new section" popup as expected. I filled in "Section Name" with "Home Automation" and left the other options blank. I clicked Save and nothing happened visually. I opened the developer console and I got the following traceback (repeated every time I clicked "Save"):

```
TypeError: Cannot read properties of undefined (reading 'push')
    at f.<anonymous> (dashy.9f0ff4c4.js:1:427855)
    at vuex.esm.js:844:13
    at vuex.esm.js:466:7
    at Array.forEach (<anonymous>)
    at vuex.esm.js:465:11
    at f._withCommit (vuex.esm.js:624:3)
    at f.commit (vuex.esm.js:464:8)
    at f.commit (vuex.esm.js:409:19)
    at r.saveSection (EditPageInfo.vue?a59e:100:1)
    at click (interactive-editor-add.svg:1:384)
```
I've tested with Firefox 95.0b4 and Chromium  103.0.5060.114 and it happens on both.
Funny thing - now that I'm submitting this and redoing my steps - it started to work... :confused: I haven't made any changes... 

Well, hope this helps identify the issue (if any).
Thanks again!

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hiya @mad-ady 
Sorry you're having issues, and that does indeed sound like a bug.
Was this the first section? From that error message it looks like `sections` is somehow undefined. Though even with the first, it shouldn't be undefined :thinking:  

I'm going to link this to #799 which is a (much needed) re-write of the whole config management process, that I'm working on atm. 
I guess that when complete, that should fix the issue

**Comment by mad-ady** [comment]
Yes, it was the first section. Note that the cause might be because I
mapped the configuration to an empty file outside of the docker
environment. I deployed with docker-compose and I used:

```
    volumes:
      # - /root/my-config.yml:/app/public/conf.yml
      - /etc/dashy.yml:/app/public/conf.yml
```
Having touched /etc/dashy.yml before. So, if your initialization creates
the file if it doesn't exist, it might skip in this case causing the app to
start with a blank config file. Might want to test if the config file is
empty, to run initialization on it.

Cheers!

**Comment by Gadgetroch** [comment]
Hi, i have this issue too with the latest docker version.
How is going ?

Thank's

**Comment by mad-ady** [comment]
I too have installed the latest docker instance on a new system - I've done
the same steps (touched an empty config file outside of the docker
environment and mounted it as a volume.

I still get the errors when trying to save the initial config.
The config looks like this (when exported):
```
"root":
"appConfig":
"theme":
"language": "en"
```
When starting up the docker container, it does complain that the config is
invalid, but doesn't seem to try to fix it:
```
Dashy    | Checking config file against schema...
Dashy    |
Dashy    | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Dashy    |   Warning: 1 issue found in config file
Dashy    | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Dashy    | 1.  must be object
Dashy    |
```

Now, the file contains just:
```
$ cat /etc/dashy.yml
appConfig:
  language: en
```

Thanks

**Comment by changbowen** [comment]
Had the same error in browser console when adding first section.
It worked after manually adding `sections:` to the initial config. Like this
```yaml
appConfig:
  language: en
  layout: auto
  iconSize: medium
sections:
```
It feels like this could be fixed if the auto-generated initial config includes `sections:`.

**Comment by bmswens** [comment]
@changbowen's comment led me on the write path.
This fixed the issue for me.
```yml
appConfig:
  language: en
  layout: auto
  iconSize: medium
sections: []
```

**Comment by atay** [comment]
There should be a fix for it, if you start with empty configuration file, then it just doesn't work
